### ISSUE TITLE
Consider providing a history of states

### ISSUE THREAD

**Issue by michaelpj** [andreabedini/foliage#1]
Based on discussion on IRC.

It seems that cabal generally expects repositories to have multiple temporal states, with users able to control which one is selected with `index-state`. This lets cabal update as gracefully as possible, and apparently just mutating repositories without doing this can hit cabal bugs (citation needed).

The approach that foliage seems to be taking today is to have *different* repositories for different states, and the user then has to select which one they want by changing the URL (which will contain a hash). It's unclear how gracefully cabal will deal with this (maybe it will bloat `~/.cabal/packages`?), and it requires a non-standard way of updating (change the repository url rather than running `cabal update`).

The alternative would be to expose a single repository with a history of the states computed from the source specification. But we'd like it to still all be declarative, so we would need to do something like:
- Reify the different historical states into the repository itself, maybe in folders?
- Have a tool that processes the *history* of the source repository in some way, and populates the repository history from that?

This is a problem for other custom Hackage repositories, notably head.hackage doesn't expose a history either (which is regarded as a defect). So if we could come up with a nice way of doing this it would be quite beneficial for other projects.

**Comment by michaelpj** [comment]
Another idea: doing a github release creates a "state" with the date of the release, the repository is built from the github releases and their corresponding source tarballs.

**Comment by andreabedini** [comment]
Thank you @michaelpj.

You say a _non-standard way of updating_ but I challenge this interpretation 1) nix works exactly in the same way 2) if you use a mutable ref, `cabal update` will work 3) having to edit `index-state` in cabal.project is no different from editing the repository's url.

Let me review the approach (including possible flaws) and get back to the suggestions about index-state after that.

### Overview

My original approach was for users to be able to point to the repository from their `cabal.project` file

```
-- by branch name, mutable ref
repository andreabedini-byo-hackage
   url: https://raw.githubusercontent.com/andreabedini/byo-hackage/gh-pages/
   secure: True
```

or

```
-- by commit hash, immutable ref
repository andreabedini-byo-hackage
  url: https://raw.githubusercontent.com/andreabedini/byo-hackage/5a8b1a7af372e9b59687bce8cd768ba3ac588a4f/
  secure: True
```

This likely needs to be accompained by the following

```
-- prevent a specification of a `index-state` in the past for hackage from messing up with the custom repo
index-state: andreabedini-byo-hackage HEAD

active-repositories:
  , hackage.haskell.org
  , andreabedini-byo-hackage:override
```

This allows a project to update the index has they wish. I don't believe changing the url and updating the index will cause any bloating of `~/.cabal/packages`.

There's a couple of considerations here:

1. What I did not realise until now is that multiple project could want to access different states of the same repository, and the repository name is global! This means one would `cabal update` between repositories, and hope cabal can handle it. Another option would be to use different names for the repositories (e.g. `repository andreabedini-byo-hackage-5a8b1a7af372e9b59687bce8cd768ba3ac588a4f`) which could feel like causing bloat. This should put in prospective with the alternatives though: the use of source-repository-packages causes bloat anyway; in my checkout of input-output-hk/plutus-apps `dist-newstyle/src/` is about 1G, and I have checkouts for plutus, cardano-node, etc, all pulling the same repos).

2. cabal-install can get confused by a package which has changed its source. I did a few experiments and I could not find a reliable way to make cabal-install notice the change. I might need to investigate this further.

Personally, I feel more concerned about point 2 than 1. Of course, if one only adds new package versions this problem disappear but I think we need a proper harness in place.

### Supporting index-state

The current state is that the tarball is regenerated at build time and all entries have the same timestamp.
To support historical index states, one could update the last version of the repo, rather than regenerate it.
The program hackage-repo-tool already supports this and I could adapt foliage to do the same.

I can be lured into supporting this, but my intention was to keep everything stateless. In the end, the repo history is already in git! I wish cabal could just read that instead.

**Comment by michaelpj** [comment]
> You say a non-standard way of updating but I challenge this interpretation 1) nix works exactly in the same way 2) if you use a mutable ref, cabal update will work 3) having to edit index-state in cabal.project is no different from editing the repository's url.

None of this argues against it being _non-standard_. You're arguing that it's _fine_, but it's still true that it works differently to how other cabal package repositories work.

IMO having the interaction mode be exactly the same as with other cabal package repositories is the gold standard for UX here. Other things might be acceptable, but if we can get the best then maybe we should do that. Plus e.g. it seems that the `head.hackage` maintainers do feel like it's a problem, and would like to support the "standard" way.

And doing things in a non-standard way means you're less likely to be robust to changes in the tool. If cabal changes so that it handles what you're proposing less gracefully, we'll be in trouble. Whereas if we do things the way it expects we're probably safe.

> What I did not realise until now is that multiple project could want to access different states of the same repository, and the repository name is global!

Yes, this is very important. In the ideal outcome, everyone in IOHK is using this repository! But they won't all be at the same state, and they will get quite unhappy if it mysteriously changes under them and stuff starts breaking (which shouldn't happen if they're using a hash, but still).

> cabal-install can get confused by a package which has changed its source. I did a few experiments and I could not find a reliable way to make cabal-install notice the change. I might need to investigate this further.

I think this is an example of the risks of doing something non-standard. 

> I can be lured into supporting this, but my intention was to keep everything stateless. In the end, the repo history is already in git! I wish cabal could just read that instead.

Well, I proposed a couple of ways of having a history-enabled package repository built from a declarative specification! What do you think of those? I think both "process the history in some way" and "use github releases to identify 'states'" might both be viable.

**Comment by michaelpj** [comment]
One final thing on UX: nobody enjoys fussing around with build tools; and they also don't like learning new concepts. If we want to sell people on using this, the more standard it is the better!

**Comment by andreabedini** [comment]
Thanks @michaelpj for your thoughts.

I had a good think about this and I reckon there's no harm in giving the user the ability to update an existing repo/index in a sensible way. To be honest I don't like the design of `index-state` too much but that's what most of users are familiar with at the moment.

Here is the design I am thinking:

- The tool will take an existing repo and update it according to the new inputs. New cabal file revisions and package versions can be added. Updated files will be determined by hash.
- The tool will warn (or error) if packages are changed or deleted, as the index has to stay append only.
- What the user does with the output it the user's resposibilty. If could be published at the same address (modifying files, breaking immutability, and allowing `cabal update`) or it could be published with hash prefix. Or both.
- It would be nice if the tool could spit out the partial hashes corresponding to every index-state. To decrease the load on downstream tooling (e.g. haskell.nix).

At the same time I am rethinking the input. I really would like a file-based way to specify the repository. At the moment I am leaning toward something like this.

- `_sources/{package name}/{package version}` is a file with content `url#subdir`
- `_sources/{package name}/{package version}.cabal` is a cabal revision

There's a bit of repetition (e.g. repeating the url for each package in the same repo) but it's simple and flexible. Declaring the package name and version beforehand is actually a plus as it prevents clashes.

I still have a couple of concerns:
- Ideally we want to keep all cabal versions, not just the latest one. If nothing is deleted in the input, the index can always be rebuilt along with its history. Perhaps `_sources/{package name}/{package version}/revision/1.cabal` like Hackage does?
- If we wanted to include the source distribution directly in the input rather than pointing it by url (not sure this is needed, cabal doesn't need an index in this case, it can already load up source distributions from a directory on disk), how would it work? perhaps `_sources/{package name}/{package version}/URL` if it is a url and `_sources/{package name}/{package version}/{package name}-{package version}.tar.gz` if it is a sdist?

What do you think @michaelpj ?

**Comment by michaelpj** [comment]
> The tool will take an existing repo and update it according to the new inputs. 

If I understand you correctly, you're suggesting that:
- `foliage` provides a way to (reproducibly) create a "snapshot" of a repository
- You can use `foliage` as part of a system to create a repository with history, but it does not itself provide the tools to do so in a reproducible way.
    - You would need an additional tool to e.g. crawl the history of the source repository and append "snapshots" at particular timestamps using `foliage` for each one.

I guess that seems fine: it solves one part of the problem. I think we will want to solve the other part of the problem, but I guess that can be a standalone tool. We can always write `foliage-repo-history-to-repo` later or something.

> Perhaps _sources/{package name}/{package version}/revision/1.cabal like Hackage does?

Yes please. It would be good to have all revisions, even if they've been superseded. Append-only!

> If we wanted to include the source distribution directly in the input rather than pointing it by url (not sure this is needed)

One use case that comes to mind for this is testing. Suppose I want to test what happens if I add a new version of the package to the repository. If there's support for pointing to literal sources then I don't have to push it to a URL somewhere, which is maybe nice.

-----

On input format:
- I think it's nice to have metadata rather than relying entirely on implicitly what's there in the filesystem. So I'd be inclined to keep the file that says how the package version is fetched. Or says if there is literal source included.
- I think you're following what cabal does in `~/.cabal/packages` for the sdist tarballs, I like that.

So I'd maybe have something like:
- Info goes in `packages/<package-name>/<package-version>`
- `meta` file specifying the metadata, what kind of source it is, URL if it needs one
- sdist tarball or literal source can be here if specified
- revisions live in a `revisions` folder.

**Comment by andreabedini** [comment]
All the above is included in a [new release](https://github.com/andreabedini/foliage/releases/tag/v0.4.0.0), see [README.md](https://github.com/andreabedini/foliage/blob/080197e9e21b77b8f3d9038ffcc4952d9cb4ad56/README.md).
