### ISSUE TITLE
Restore flake on other systems

### ISSUE THREAD

**Issue by michaelpj** [andreabedini/foliage#53]
We use the foliage flake in CHaP, and so people who aren't on linux can't get a shell at the moment, because the foliage flake only supports linux.

Maybe just reverting https://github.com/andreabedini/foliage/commit/ae45f208a2b13e554150408a00662918261172c9 ?

**Comment by berewt** [comment]
Here is the issue I have in CHaP at the moment:

```
error: flake 'git+file:///Users/nicolasbiri/IOG/cardano-haskell-packages' does not provide attribute 'devShells.x86_64-darwin.default', 'devShell.x86_64-darwin', 'packages.x86_64-darwin.default' or 'defaultPackage.x86_64-darwin'
       Did you mean devShells?
```

**Comment by michaelpj** [comment]
Ah okay, that's a CHaP issue, but we'll immediately hit the foliage issue also.

**Comment by yvan-sraka** [comment]
Is this would be somehow linked to https://github.com/andreabedini/foliage/issues/47?

**Comment by andreabedini** [comment]
I think the evaluations are too old and have now disappeared from https://ci.zw3rk.com/jobset/andreabedini-foliage/main/evals but I had removed the other systems because I could not get them to work. I had the following in the flake to make a static build but I am not sure it works correctly

```
        pkgs-static-where-possible =
          if pkgs.stdenv.hostPlatform.isLinux then
            if pkgs.stdenv.hostPlatform.isAarch64 then
              pkgs.pkgsCross.aarch64-multiplatform-musl
            else
              pkgs.pkgsCross.musl64
          else
            pkgs;
```

Happy to revert https://github.com/andreabedini/foliage/commit/ae45f208a2b13e554150408a00662918261172c9 but then I'd appreciate some help in getting it work.
